<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>RestfulTweaksShopRefreshFix</AssemblyName>
    <RootNamespace>TravellersRest.ShopRefreshFix</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src/RestfulTweaksShopRefreshFix.cs" />
    <PackageReference Include="BepInEx" Version="5.4.21" />
    <PackageReference Include="BepInEx.Harmony" Version="2.5.1" />
  </ItemGroup>
</Project>
